### ISSUE TITLE
Soft WDT funktioniert so leider nicht

### ISSUE THREAD

**Issue by thedarkman** [bitluni/WeatherStation#1]
Hi bitluni,

ich hatte Deine Wetterstation (als prototyp) nachgebaut und versucht sie eine Woche auf der Fensterbank laufen zu lassen. Leider ist sie maximal einen Tag durch gelaufen, aber auch nicht wirklich reproduzierbar abgestürzt.

Habe dann die einzige Stelle mit einem Test Sketch getestet, nämlich das WDT "reset" durch die while-Schleife. Ja, das esp wird resettet, man sieht auch schön im Stacktrace dass es passiert, aber danach ist es weg und kommt nie wieder ...

Ich mach den github-issue nur auf weil man auf Deiner Homepage keine Kommentare schreiben kann in dem Wetterstation Artikel und ich bei youtube so einen langen und formatierten Text nicht schreiben wollte.

Ersetzt man die While-Schleife durch ein `deepSleep()` Aufruf, kommt der esp nach der sleep Zeit wieder und versucht es erneut ... Wenn der broker komplett weg ist, bringt das auch nichts, aber besser als in den Garten gehen zu müssen zum reset.

https://github.com/bitluni/WeatherStation/blob/50dbfe939cb7e247ca1b063af0dc26997448ec38/weatherStation/weatherStation.ino#L111

```
Connection failed
Retrying MQTT connection in 1 second...
Connection failed
Retrying MQTT connection in 1 second...

Soft WDT reset

ctx: cont 
sp: 3ffef840 end: 3ffefa30 offset: 01b0

>>>stack>>>
3ffef9f0:  00000001 3ffee6cc 3ffee94c 40201cf6  
3ffefa00:  3fffdad0 00000003 3ffee7d0 40201dc6  
3ffefa10:  feefeffe 00000000 3ffeea00 40203e28  
3ffefa20:  feefeffe feefeffe 3ffeea10 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
```

Viele Grüße
  thedarkman aka jjk

**Comment by bitluni** [comment]
You are right. 
This part of the code is taken from the Adafruit MQTT example... I didn't look in that close enough to see this possible issue. 
I'll commit your suggestion. Thank you very much.

**Comment by bitluni** [comment]
committed your suggestion. thanks

**Comment by thedarkman** [comment]
Just an update after nearly two weeks, esp8266 runs now like a charm. Seems it got really stuck once a day pre fix. I now save data to db also for long term storage, instead of only having them in node-red; also done with node-red of cause

PS: waiting for the next camera video ;).
