### ISSUE TITLE
Voltage measuring not working

### ISSUE THREAD

**Issue by ghost** [bitluni/WeatherStation#2]
Hi!
How do I measure the voltage of the ESP? Do I need to conect a voltage divider to A0?
I have uncommented the `//#define PUBLISH_VOLTAGE` in the code but it constantly shows 3,55V.

**Comment by BavarianBarbarian1** [comment]
I did it by adding a 100k resistor. Works fine with a 18650 Li-Ion battery to calculate the voltage, 1V equals the input value of 1023. See https://arduinodiy.wordpress.com/2016/12/25/monitoring-lipo-battery-voltage-with-wemos-d1-minibattery-shield-and-thingspeak/ for more information!

**Comment by ghost** [comment]
@BavarianBarbarian1 sounds promising. Gonna try that out asap.

**Comment by DPR7** [comment]
You need something like this to begin with ;
// ADC setup
int bat = 0;
int sens = 0;
int volt = 1;
ADC_MODE(ADC_VCC);

**Comment by DPR7** [comment]
Another solutions starts with  ;
// ADC setup
float bat = 0;
float sens = 0;
float volt = 1;
ADC_MODE(ADC_VCC);
